server:
  port: 8084



spring:
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

zuul:
  routes:
    service1: /service1/**
    service2: /service2/**
